### ISSUE TITLE
Mapping ambiguity

### ISSUE THREAD

**Issue by ruthenian8** [ruthenian8/bagvalal#7]
What I can tell from inspecting the dictionary data is that there are several possible ambiguity cases:
the sign "ɬ" may be transcribed both as лӀ and лъ
For instance, a converb derived from the word "to crawl" is written like ɬēbo
Meanwhile, in Magomedova the verb "to crawl" looks like лӀардила
Yet it is necessary to note, that Magomedova also mentions the variant with initial лъ- as a Kvanadian dialectal form, so the ambiguity may be due to the dialectal difference.
In most of other cases ɬ generally corresponds to лъ
The other thing is that the problem with the nasalized "n" is not restricted to the example I showed during the session, since there are plenty of cases in which the possible nasalization is not denoted in Kibrik's transcript. The example I found this time is the word "door": гьуᴴс̄Īýлъ and huns’-u-ɬ
As you can see, in Kibrik's variant there are no features that let one predict the nasalization.
Aside from all that, the session convinced me, that generally this problem is nowhere near as harsh, as I imagined it was.

**Comment by agricolamz** [comment]
About nazalisation

Kibrik 2001: 40

![image](https://user-images.githubusercontent.com/15956515/108947771-31df5000-7672-11eb-899b-6e74d4a465f9.png)

**Comment by agricolamz** [comment]
About *лъ*: it is sad, but it looks like in Kibrik et all they didn't distinguish affricate tɬ (лI) and fricative ɬ (лъ). This is a big surprise, since it is present in other Andic languages, and it is not so hard to detect, but I guess this is not a result of researchers ignorance, but rather orthographic failure. Avar is the lingua franca in this part of Dagestan, so all of them taught Avar in school and still use this language communicating with strangers (some of Andic people even think about themselves as Avars, because of SSSR politics). Therefore they use Avar script and sadly Standard Avar lacks this distinction (however most of the dialects do have it). So I stipulate that the observed result is just a consequence of Bagwalal people lacking this knowledge about ɬ and tɬ (and sometimes it is hard to explain to the native speakers).
